name: Validation Tests

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  run-validation-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
        
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run Attribute Search Tests
      run: |
        python validation/search/attribute/attribute_test_suite.py
        
    - name: Run Importance Search Tests
      run: |
        python validation/search/importance/importance_test_suite.py
        
    - name: Run Sequence Search Tests
      run: |
        python validation/search/sequence/sequence_test_suite.py
        
    - name: Run Step Search Tests
      run: |
        python validation/search/step/step_test_suite.py 